name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "packages/frontend/**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  frontend:
    name: Frontend build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: packages/frontend
        run: bun install --frozen-lockfile

      - name: Build with Vite
        working-directory: packages/frontend
        env:
          VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
        run: bun run build

      - name: Deploy to Cloudflare Workers (wrangler)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/frontend
          command: deploy --assets dist --name ${{ vars.CF_WORKER_NAME }}
